### ISSUE TITLE
Add possibility to narrow down key space of KVNamespace

### ISSUE THREAD

**Issue by kulla** [cloudflare/workers-types#113]
Sometimes a KV namespace might be used only for a known subset of strings. It would be great to define it directly in the type of `KVNamespace` to have typescript checking whether we have only used the keys of this known subset.

### Example 1

A developer might want to use a KV namespace to store settings which can be changed through a special route. In this case it would be great to have TypeScript checking whether the used keys are fine. Example:

```ts
// Only the keys "enabled" and "color" should be used in the KVNamespace
const settings = KVNamespace<"enabled" | "color">

// fine
settings.get("enabled")

// we would get an error here and thus we see that we have misspelled the key
settings.get("ennabled")
```

### Example 2
Usage of [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) to define the key space:

```ts
const kvNamespace = KVNamespace<`data${number}`>

// fine
kvNamespace.get("data1")

// errors
kvNamespace.get("dataa1")
kvNamespace.get("data-1")
```

**Comment by koeninger** [comment]
The key provided to kv get needs to be a string, not an arbitrary parameterized type K.

If you want to restrict it further than string, I'd suggest wrapping it with your own functions in your own project-specific code.

**Comment by kulla** [comment]
> The key provided to kv get needs to be a string, not an arbitrary parameterized type K.

Good point. In fact I thought that `<K=string>` means that `K` must extend `string`. In my original PR this was in error. I will write `KVNamespace<K extends string = string>` so that only subtypes of `string` can be used as `K`. See [this playground example](https://www.typescriptlang.org/play?ssl=1&ssc=48&pln=1&pc=23#code/JYOwLgpgTgZghgYwgAgNIDUBycC2EDOADohADyrIQAekIAJvsvmFKAObIC8TL7AfMgDeAKGRjkAegnIwAT0Io6EGKGBhgAexDIAFtAjCAvsOFTkAdw1QA1vmEItzZHGQAuNFlwFiSUgCIYDQ0-ZAAfZD8AIzgoPwFuQWNTaWgoK3tHMGRI9wxsPCISUkiggBsIOBB4oUMgA). Thanks for your correction :smile:
