### ISSUE TITLE
HeadersInit -> HeadersInitializer

### ISSUE THREAD

**Issue by lookfirst** [cloudflare/workers-types#116]
For some reason, this name changed from 2->3.

Changes like this should be documented. Please.

**Comment by vlovich** [comment]
In the latest version we still leak the non-standard names unfortunately. However, as a mitigation I've reintroduced the standard names as aliases to ease porting issues hopefully (#120). Unfortunately it would be annoying to try to figure out how to get rid of those internal names with our automated type generation vs just fixing the name in the runtime.

If you're still having problems, please reopen or file a new issue. Sorry for the churn this may have caused.

**Comment by lookfirst** [comment]
It would be nice if there were unit tests or at least a sample project that depends on the "standard" values so that this doesn't become an issue again.

**Comment by vlovich** [comment]
That's a good idea and an area for constant improvement. I'm on the runtime team and was just updating some of the automation pieces and my background is primarily C++/python. I personally unfortunately don't have time/experience to add tests for some of these issues but I'd be happy to review such contributions.
