### ISSUE TITLE
Result of WebSocketPair can't be destructured

### ISSUE THREAD

**Issue by CodeWitchBella** [cloudflare/workers-types#147]
## Steps to reproduce
- Install `"@cloudflare/workers-types": "^3.1.1",`
- write `const [client, server] = new WebSocketPair();`

## Actual result

![image](https://user-images.githubusercontent.com/43038212/141702746-848e6e5d-c30b-4212-8611-207f1654a7c0.png)

## Expected result

Code above to be handled the same by typescript as 

```typescript
const webSocketPair = new WebSocketPair();
const client = webSocketPair[0];
const server = webSocketPair[1];
```

## Cause

This is probably because the type for WebSocketPair is 
```typescript
declare const WebSocketPair: { new(): { 0: WebSocket; 1: WebSocket; }; };
```

instead of 

```typescript
declare const WebSocketPair: { new(): [WebSocket, WebSocket]; };
```

**Comment by lukeed** [comment]
These are not the same thing. The WebSocketPair returns an object with `0` and `1` keys, not an array with two items. That's why `pair[0]` and `pair[1]` still work

**Comment by CodeWitchBella** [comment]
That makes sense, and it indeed does crash when I try to destructure it directly. I see that docs use Object.values as a workaround, which is good enough.

Would it make sense to add something like (untested)

```
*[Symbol.iterator] () {
  yield this[0];
  yield this[1];
}
```
  
to support direct destructuring? But this would probably go as a feature request on another repo :-) Feel free to close this.

**Comment by vlovich** [comment]
CC @jasnell for visibility.
