### ISSUE TITLE
RequestInit and Request cf properties are different

### ISSUE THREAD

**Issue by AngusMorton** [cloudflare/workers-types#15]
`RequestInit` and `Request` cf properties are different, this makes using patterns like `return new Request(parsedUrl.toString(), request)` impossible because `Request.cf` is not structurally identical to `RequestInit.cf`.

I suggest we converge on a common `cf` type for both `Request` and `RequestInit` to support the above pattern.

**Comment by ispivey** [comment]
I just ran in to this as well!

**Comment by ispivey** [comment]
I'll take a shot at reconciling these this week.
