### ISSUE TITLE
Create and publish v2.0.0 release to npm

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-types#19]

**Comment by dshnkao** [comment]
Hey,
Any timeline on when this will be published?

**Comment by SerCeMan** [comment]
Hey, @ispivey! Would you be able to publish the new version to npm? We're currently seeing errors due to https://github.com/cloudflare/workers-types/issues/15 which makes the use of the types much harder.

**Comment by ispivey** [comment]
Hey folks! We're planning on getting this out the door on Monday. Thanks for your patience. This should start getting faster too 😄
