### ISSUE TITLE
module worker typings support

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-types#204]
[Module worker syntax](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/) is currently not supported by @cloudflare/workers-types.

This means that users don't get the benefits of autocompletion or type checking when they use the new syntax.

References:
- https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#syntax-module-worker
- https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/#syntax-module-worker
- https://unpkg.com/browse/@cloudflare/workers-types@3.4.0/index.d.ts

**Comment by GregBrimble** [comment]
Module Worker type should be here: https://github.com/cloudflare/workers-types/blob/master/index.d.ts#L553-L556

**Comment by eugene1g** [comment]
FWIW, I get full types when I declare my Module worker this way -
```ts
// worker.ts

const workerHandler: ExportedHandler = {
  async fetch(req, env, ctx) {
     return new Response("hello");
  },
};
export default workerHandler;
```
