### ISSUE TITLE
WebSocket types are broken

### ISSUE THREAD

**Issue by vlovich** [cloudflare/workers-types#212]
This happened a few weeks back. WebSockets are no longer abstract which may be part of the problem. Ticket opened internally at Cloudflare as this is likely something that needs to be fixed internally as well as removing the abstract annotation from the override.

**Comment by vlovich** [comment]
cc @threepointone

**Comment by threepointone** [comment]
Noted, thank you! Marked https://github.com/cloudflare/workers-types/pull/205 as blocked.

**Comment by threepointone** [comment]
released, closing this
