### ISSUE TITLE
Add missing properties that can be in the `cf` object on an `event.request`

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-types#23]
We should add missing properties that are documented here: https://developers.cloudflare.com/workers/reference/apis/request/

These should be added to the `CfRequestProperties` interface.

We should also update the interface to reflect that much of the geolocation information is optional, and may not be present on every request.

Missing properties:
- [x] clientTcpRtt
- [x] metroCode
- [ ] isEuCountry (not documented yet)
- [ ] weight
- [ ] exclusive
- [ ] group
- [ ] group-weight

**Comment by ispivey** [comment]
... do we actually include `group`, `group-weigh`, `weight` and `exclusive` ? I haven't been able to reproduce that myself, even using Firefox. I just see those fields as part of the `requestPriority` string property, like `"requestPriority": "weight=42;exclusive=0;group=13;group-weight=241",`

**Comment by ispivey** [comment]
I'm going to close this as complete for now. I'll file a follow-up for isEuCountry.

**Comment by harrishancock** [comment]
I suspect the `group` and friends were implemented as documented, then documented, then refactored. :/

**Comment by fixingitnow** [comment]
@ispivey I"m trying to use isEUCountry, but seeing this error 
_'isEUCountry' does not exist on type 'CloudflareRequestAttributes'_
did you get a chance to add it to the interface?
