### ISSUE TITLE
Missing `waitUntil` on `v3.9.0`

### ISSUE THREAD

**Issue by 2fd** [cloudflare/workers-types#233]
In the following commit the `FetchEvent` and `ScheduledEvent` lose the `waitUntil` method, as far as I know it wasn't remove. Or it was? if not, we need to recover it.

https://github.com/cloudflare/workers-types/commit/edaac154491a2ef93326ddc0b95c830193abb9f8#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8L623

**Comment by maxshirshin** [comment]
Should `FetchEvent` inherit from `ExtendableEvent` instead?

**Comment by michalkorotkiewicz** [comment]
We see this too. The whole CI/CD stops working because of this. Please fix this. We are staying with 3.8.0 until then

**Comment by jasnell** [comment]
hmm, looks like the auto type tool isn't picking up the fact that `FetchEvent` extends from `ExtendableEvent` now. Take a look!

**Comment by threepointone** [comment]
This is released in `3.10.0`, closing!
