### ISSUE TITLE
R2PutOptions should have `sha1` key documented in Cloudflare Docs.

### ISSUE THREAD

**Issue by syumai** [cloudflare/workers-types#244]
There is `sha1` key for R2PutOptions in Cloudflare Docs.
* https://developers.cloudflare.com/workers/runtime-apis/r2/#r2putoptions

But current type declaration doesn't have it.

https://github.com/cloudflare/workers-types/blob/3012f263fb1239825e5f0061b267c8650d01b717/index.d.ts#L1128-L1132

It should be like this (or documentation is wrong).

```ts
interface R2PutOptions {
  httpMetadata?: R2HTTPMetadata | Headers;
  customMetadata?: Record<string, string>;
  md5?: ArrayBuffer | string;
  sha1?: ArrayBuffer | string;
}
```

**Comment by KianNH** [comment]
`sha1` is removed.

https://community.cloudflare.com/t/2022-5-12-workers-runtime-release-notes/383116

**Comment by syumai** [comment]
Oh, thank you. Then documentation should be fixed.
This does not seem to be a problem on the `workers-types` side, so I will close this issue.
