### ISSUE TITLE
Generate exportable version of `workers-types`

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/workers-types#299]
once overlap between workers and standard types is calculated (https://github.com/cloudflare/workers-types/issues/298):
* remove overlap from workers types 
* produce separate package for overlapping types

**Comment by penalosa** [comment]
Following internal discussion, the scope of this issue has changed to producing a separate, exportable, entry point to the `workers-types` package, which developers can use in conjunction with `lib.dom` or `lib.webworker`
