### ISSUE TITLE
BSD-3 License

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-types#31]
👋 

Thanks to everyone who's contributed as workers-types has evolved from one Cloudflare employee's project to a community project fully supported by the Workers team!

We will be releasing the workers-types repo under the 3-Clause BSD license ("BSD-3"), so we are asking all non-Cloudflare employees who have already contributed to workers-types to license their contributions under BSD-3. The relevant PR is #30 .

If you agree, please add a comment below stating "I hereby license all my contributions to workers-types under BSD-3." 

Contributors we'd like to hear from are: 
* @ashnewmanjones 
* @EmanH 
* @GregBrimble 
* @RReverser 
* @leo-ar 
* @trjstewart

**Comment by leo-ar** [comment]
I hereby license all my contributions to workers-types under BSD-3

**Comment by EmanH** [comment]
I hereby license all my contributions to workers-types under BSD-3

**Comment by RReverser** [comment]
I've been a Cloudflare employee at the moment of contribution, so I don't think I need to sign anything explicitly?

**Comment by ispivey** [comment]
@RReverser no worries! I thought that might've been right after you left, but if you were an employee at the time of the contribution, that's fine. Hope you're doing well 😀

**Comment by RReverser** [comment]
Oh, actually... it does look like it was right after (in 2 weeks or so). Weird 😀 Anyway:

I hereby license all my contributions to workers-types under BSD-3

**Comment by ashnewmanjones** [comment]
I hereby license all my contributions to workers-types under BSD-3.

**Comment by trjstewart** [comment]
I hereby license all my contributions to workers-types under BSD-3.

**Comment by GregBrimble** [comment]
I hereby license all my contributions to workers-types under BSD-3.

**Comment by ispivey** [comment]
Thanks everyone! Really appreciate your help.
