### ISSUE TITLE
IncomingRequestCfPropertiesGeographicInformation makes geo property access an error (regression from 3.17.0)

### ISSUE THREAD

**Issue by maxshirshin** [cloudflare/workers-types#311]
`IncomingRequestCfPropertiesGeographicInformation` (as part of the `IncomingRequestCfProperties` union type) is defined in such a way that it treats accessing of geo fields on the `Request` instances `.cf` field as an error.

Here's a [Typescript Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgdgYwPYFsCWcDmAlCBHAVwgGdgBhAMwAUAnJSG4NEgcQiUxoEMwALNBPApIaKLkyRwoAXgBQUKAB8oAbwC+8pas0KFyAnGA0QALigAiACoBGcwG4dUDQuUrHepAaOmopGhkwHXV00YgBRAFUyT0NjAH4zc1sg4KhkQwwIQzM-AJTghDRQBN8jPPcoMCRSLgAbaIATCBLcrHzdWvEigiaWsraK2slMbt6c-sCKphQIAC9JZvH-AdSoGggRyT7lydX1zbhGxdKd9oUZoyQj7fLgtQdZdNI0ijN4ZHQsXEIScmo6BhMVjsTg8fiCODCURdSQyVRqKBcYhQAwAazgSAA7lIkbBEKgAt8iKRKLR6BBGMxiGwONw+AIhCIxBI4A8APRsqCgSBQCl0GhQAAUACMCMBeQAPSAIYAQBpcpBQYXQLjC2rQYCK9ZceUAOkKoCgADc6kQAJSPSTEJDq3VDTCChAUfVFEBmhxAA) for an isolated case that demonstrates the issue.

This makes e.g. this code to raise a type error:
```typescript
/* request is a Request instance */
console.log(request.cf?.city)
```
Error: `Property 'city' does not exist on type 'IncomingRequestCfProperties<unknown>'.`
Expectation: read access to any geo property shouldn't be treated as a type error.

This is a regression from v3.17.0 where it worked fine, and is likely related to [this change](https://github.com/cloudflare/workers-types/commit/17b6d16e2b7d0e8605ae0ed2e704336ef89c2c47).

**Comment by Qantas94Heavy** [comment]
Technically you can get the original to work if you perform an `in` check to narrow the type down, e.g.

```typescript
if (req.cf && 'city' in req.cf) {
  console.log(req.cf.city);
  console.log(req.cf.continent);
}
```

However this can be sometimes unwieldy, especially given `?.` is not used for type narrowing.

**Comment by caass** [comment]
I think the new types are technically correct -- the way that the geographic information is gathered in Cloudflare's edge, there really may not be a `city` property. Is there any downside to @Qantas94Heavy's suggestion of using `city in req.cf` for type narrowing? You could potentially write a function like

```ts
function hasGeographicInformation(cf: IncomingRequestCfPropertiesGeographicInformation):  Extract<IncomingRequestCfProperties, { country: Iso3166Alpha2Code }> {
  return "country" in cf && cf.country !== "T1"
}

// works!
if (hasGeographicInformation(cf)) {
  console.log(cf.city)
}
```

[Playground link](https://www.typescriptlang.org/play?#code/PQKhCgAIUhhALApgYwNaQJYDNIBcmYB2yA9gLYaEDmkATogI4CuiAzrpPAIauRWIkqtLgAd4GZESwlaZLrgwlCUEMHBYmxBUs48A4gKGjxyAJKFps+YsIAKZFgBckc6QrUASoxbtYWAAq0JCKItApsBoLCYhLmlnLahACUzg6YvACiAB64wsi4ADyu5JRUXsxsuH6BwaHhrAA0kADekKSauQCezqasJADMAIwAbMMAggA2YlwATLAkACaIkAC+AHwtUHSIuEy0hJAARO2EXYdEbTgAZFeXAHQnXZAAhAC8r0cAKoOH4Cvg4FIhHYlx6xBKnm8lWqQRCYQwEUM0RMcRkCRskA+zRWkB4kE0qEIJAA7gc8cV3GUob4ArC6gjWJEjDEzBY0dYlABuAHYSC2biMpHGWJsqyJexYJJJTZAvoTRB3CaCCUPDC4TpJbn-AE68CgSAAWiNeE6IV4pBEnWAIh4uEQC0gWCCZEgxJkqFCrAN6rNhuNql1OtAEGgkHKPg4ZB2XAW8i4kBEQQAbhglg6AEadOBKpgLLATLj0ADkvHt-DuKjUPuWFNK4ehtNq8LYBQAEiR2ABZaOx3Dxj4EomkjavLa1yEVGk1OH1ABCPGWVy2kBc4Mp9andObrFnJFwna4hC4-Cjpwyp1CiYwrEXy9Xbjr1KqjZnDNgObzBfoADEZABlLguD-c87VoK8bzbDt9x7OMNiXFcV3HKlJ2fad6URKJhVZeIOQOeCEKQjdUK3ep3xIXN80LRAxmQZA2FYAB5WgxhEDA-3ERAJgWblwEoUCsC4Oj7whZCIxhJs5wXTYV2DZcYAAbTGP8ADkAF1+VwXARFYRxgGAYkDLuDBDy4O4ZCoYAeFYDAqEIU9cFYSyvUIJgyHTT0nINFy3M9O4sngXAyAmaUSBwfBlkoB9qG2FCKwQkMVxgAABRAsi4MgRHlSB+gATgAVgAdgAFgKuS1BXHhCGcbz3NobkZLAOTIE+AhzMPDAAC9cNdEx4EgElgTwAglOU-qwoISKRJiiM4sSpqUrSjKssOPQSEELKyNzX54vK3FGNoKh2q6xJnHYWhSnqyBZPi5rWvOqhKC4CZICTJ6WDGoblgAAxouiRFwA1z1IBZSi+zhEBjUJMBwTbPyoyAyEWbAEQdNVZugebUvSzLlkOKgOowEQmiWSi7SadNaG2xLduQCYEVOX7EH+oGkeoAB+U7cgurZrsS27lhqqHQoRjAJjpm8gQWXg1TwNb0EsT7psqWXtkEvrOnI2hXXdUJ0YS0MFuxrKZhmMqtlp+ncE+ZARA8TSOcgQW6p5xqbpa5Z8HoRADXlTSofk0wxk+MZ1ICrSdL0xBCDuYkMFQQn7WMsyDv0uOMGAQPg4AfS4DAwJkXAs+BxAkia3P87CNpFmWYXwsgXt4zoi8tfweRFfoFDODRuTMcWnGjgAEW-AB1KnoBpkglU587qEu3nQy8RM2CjhzFaYbTcghsgS22VgRCUG8Va4Jr5M+WB-EgL6PSZp6MCTRAwajVhWGPRBQ807TdOAXAuJEZOLNbAxYenwGLADPv4A0ABpRAN86b3wNIA4BoCSD31oCmRAxI7gBSCqXG6TpyBtA-JRegesmq-i1m6WgHpaC8FjvgR2JB8Qb3oOlJo+BryulFs9J6xIuCdF4O5S+gwvqkJuobJayx+hmxXGWRARFoFM0mHfRAf4+y7B0sJdcT5xKvjYBkBY-B5EwJEEo++qj5BMFYHPV2fN3aQFbJ8T4F8ai4BIKQZ6dcO4RnxDeBYoi+biP7ocBxTjgAzDHgGFcYcRAuLcZPae3MGr6xgHYimJIby0ANF4yo9oEznRkGqTq3VKA4USBcTxT5+rpgAFYoFwP40MpgcBEikOyMpvDeA3lwMTRAAkmATFXq4xWiAMrqkgGdUol9DiHC+j3MRWMJFHGJIgGyAVXiDByjMTkqVaaWOUa8AADJyIQ5ERCvH6McoI68DTLNWbgdZMwCoRMgElEmXB+kcGmdIpW7BAiKHOuqBJs8XbJP5s1AAMn+F6noMS1wIECQgdSMRDNhsQhUTVzA-NXhk++DoUFQ0yrnC8OQ+R0PgORDgnxIVJDYeIXgiYJJZg4XXEZ-0swTOil9aZIi5kBIWUEqlf4kyDDuP0CJu0f6sAAGowqUECqg1jQV2OQITJAWsFZ1wRUinQKKiFfnRTdTF2T2CdNCLi-qqCEwFj4qlDgtgyUUohX+GlQ0OEMpnEy3gLLRnsq5py7lDTkr8uWmMDIYwB4GlDX+QYMwAAcBo9CwE7AaP8rYxgzDysMcVWxJWwFVaEeViqmrdj7A3KupwiWTLrvJL6rYMjgvBQxL679w5fwMpg2gWBkAGkTq42g-9gCduQIOrteUZhFWGAAYglokA0BU7hFTuCKmY0pDwOhrd+UwylTCpoyAPZtGlW16XbXcIdPaQZ9oHUOkdyAx0Tundqwgc6F13BytKJ+L9+C8HwS6dhvBjW4B3oK3QhApbcA9IGlw40IprkmQB10eIcW5PxVrQlNqSX2rVOSpglLqWuu-QiLi6R8Sgd6ZQe0esJUTFYNkfeYR7RjBw0gU4Eh5AyAdoRbRL50I0ayHRu0CxGPhRY8gNjtAS0xjjFqHkzcBJCU4yhHRPHdz7hMieFe85D7NBBU1VF+rACYBLweS8p77PWFnRMIRL1Qts-npJYpmmysAeHqqiDxyDAHTHuRyQI-oOQ83uA0rBSD0GANKVuHB4zwbcGwR0zpcSQE890pq9Al43gvA6PEh4iB2n4Kh0ITc+z8ASzsZZUchFg1sE9RGIILN9koBMLM8BXKHlwXzNdl8co5Qq1VqCbQ6hEoa-FxLSRIOBKynlIq3ygsyEQNVVytUi03TGAlta8osuvQmO9cLxHcjvV5BUzu0Xv1xfjFQNaGY9xNDph6SAq11o1y1rOUoetICdl68gSxriow0LaOSjsHtGFPSVMSfDeBhBYCwBIO4kByEIxm-XaMotGjjJgZAU+4PIeSB-ZAQkA0VsORsxHYA9nOKOec+ROGJC3DAEh-QXhYtgC49JAaa8rAfAGjXQaASDBgCTvJcSA0CwSBsC53nDBQOsn9JF9wUD8pvQY4kFz50BomdPsS6wEb3zUHI3tCp5wnnJ4Q0IItvmy2DdrYOBtrb3AODMtoHt6DWL+r3UenaY7BDj43T01RA02vIe5IZVkdlZqJAGupubGQdH5CIBqEH-Xq2jcm9DGbhP623oextzvXbEVHfwYSMgJARnIdZVtVHayB9CdfxJ0qOETnaYU7RW5sg-m-P0CwKEKOdFgDsGsN2+gfQ9h0UctKBWchCBZmrLwYWPeFCSH75rIflGtgz4kF4AftA6Lx8N4eaTvFZOCRrLBicYluPbhUweI86nTjSSujYhebAPlT5hi54svAVOvbUyMleuIjwNesqwb5RLC-V+eyMEKKUSBsNCM-PcYAq-XATTRAJPGAAedeOmUTO0D6L6IAz-eyO4abegHleKeaJYJedA+0b5C2FeT4e3dgP8YLWbR2ebUIXfG1TtA-TRR8RTU-OcGAnAleECS8c6G8LYUvUDXgBTE-KAng1TS-L-a-bTJJJqNfR-D6b3V-SAd-WAuQiLX-fha8QA3g2Q0Ajg4-SAkiBkc-Pg04BAyAW4BQhCeeU3NHAAKTGH6Bh1KEEL4krzs0QAc1r3Jwon1Sbxb28yUF80cmqS4H6FF2oC8NOFCxViQCmDyVClFmWD3hQGRkkD-D-HBTAUhUIUtgAIQja2QCCGfnrmwHb3oGvyWHYFdwxFMH8GR38ALmR3awAA08oDkco+t4RMdo8nM7xx47woj+hWweB4BC0tgVgWD995Mj8IDNwJI3wX9EByEAIgIBCwIhDEBIIuwYI+wNh7D54YBYBPsCEoxS04wUcOA4QDRyUQRKA0c1DlgFYti-wfDic-DScAj68gjXNqcATKdvZLADRCVcB4hvN1iucZBAtAJh9IMWoOF-ciMOElBBtUtv9eQNYmBdB75swG99VHQZBIBPjIAo4uB0x5Q8UDg8StZBJHgy5QNIA8SCT3jJ5gdclq0vExcHR2AmYvVGEqSaSIpcB1JD1bMfj-DfIQTG9gTYTwTIToTgB5T9U4TMkX4eBidyAiVAt15+M1TLiyADRrjJM+xQtNcdotgnjoIbi+xnB2xDiHSuB5j+J2CJCzDVi2A3jGZn4mIWI2IOIiNTi78YBUQxQMRqTHVNU6Zv9atsjo88ll50sVY3jkS6ViN94RB+lo8HRiRmNFZJpKQncOEkM8VLVgM9lqAmoVlwotY3jIB-Sp8tYxh-BTBySQyHRbAyBBVWtQx2s65sS0zcjwV+iFBBiMCBR4sNtUwT5YB6Qpzlg-xQhjJnplImDaBviuJRBY544Qj9z05FyBjWM7QABSGYA5Vc86J6S8g5TcnyWgAcmAWwDAO4BUJoIkDgL6FyMWMGMkrlGZa0uaG6BiBs2OG8JoeMLpD6QlOiclLiKGK3GLeGSxCjXlUMOxd1OoLML6WrQIVMgTMGWOMWYrO4lWLlH4Ei5jJqOuEgGpOpbM4IPMgTPkd8hURWGMwkyWQpA+V0DvBGHYEC0YlcXNeMhmJjRwO8AAHxMOWOIh9NYEFXfEtiE3gFkvkqIiU23BUoktwHUv8ALAQsniWGdm1GuhgAkzLRjJw3bifCA0KJlzAy4A9ErD3w9MWPAO0u4IZFowLgYyYxXjPJkGstuLDKVXhX0p3hrTrQbSbSEuflfm+JPTPV7RkCvS7RvTvSnRnRsGfUXWXRdU72rlRgOCQDSiWBVTkAmEwqDT7mWiKiKn6AKhmHTGiLygEhjQKl6JmEGAWCGFjSwH6CKmQBjSwEGDyjygWGQFjQKnTGGFjRmAcH6GGC4AKhygOQcEAn6Harmpaq4EGHTGmuzRXEoNOEmLEPAwYI5QVR0zdgICQ1oBitrXrUbUfnomSqlKJ1Sq7XPTVAyvMhvWyvHVysfQKqXTuBXSaBKrTAuAqshmqqejqpeWDVxiaparao6q6seV6v6sGuGtGvGsmumtmvmsWuWuGrWo2q2oEmiL2oKgOqOpOqmzNVCEupco9BmMUIeuWHOsAyMy+k3W3V3X3USs-Tfm+rbUMjSovUBpTmvSHRyofXyHyvnUXTfRhvBDhpeIRqqowBqpRrG1xgOVjSKhgVjQORmHb0GBGqGsWqWqvMQBmC4GGAOSKgOS4AOTynTD6s63WuGEGGGv6AcAKjyn6GpPTCOoOQOWGA2pmAGqwFjXTFOqKJXm-EoGvCQAWG5tv0ioyLZuesFuFp3TrTFo-S+uiR+plr+vSv7SBsVtHVBpVtnXVtfWKu1tyV1qxn1sNqIPmQapNrNotqtptrtqwAdpNgOWdtdvds9u9t9o2RygDqDv6BDqwDDojvTCjvTBjrjs2UTuTtTqeozsICzvtBmIstdhgCZGRAkHrluNso4AOwjB3gKQemjncurC0q4ykIZFvqwkjPRB0FHBXDkvsNKP1GUkYX4EwhZAfr7AQ2-XIlZI1QmiWKxWh0iQQn+DAZv0gbADBUeFoCzGLimW+BmWI3QodAVgA1bJskaOih0BAQ8HD1KLOpQa6GcEOAocuhXFwcgHAZGLzuEawoIADj-AYmyhGGGANEGGbKmG4EgBmBSsMmvBIAHXUYNCGFGANGIc6D0eric2wWCirg6BIariWHss7nftd1yR-XRlKP1icagzZM1m1ioShg4XkiBEhyoD2B5MB1oiZkpQYlYa1VVorylr0jZxEH40CNBJCPgGHSjgNEsUsnhFpjYDCQOTXtjpyn6AOQNAAFVSMaE+xQNSgDQ3iDRPh4TYn+MOdQMDQGIz6lADQPAKVSgXU-0EY+FcRqNGFBEuUKGvomhKAQZ0DJlItKlttbGjw2KUNmownHH+72HGln9iT4YOFNBqSsohklhQJ3BlhCzBKX7lZ5n8zQccKwhPV+oKA-Y-FRHnGB6jZcY9BZwx4nHdpSj9Geg+gdHxhFHZh5glg+GHC78XGmkUy0tulrmSImVKmyCvUbdrHvFLm2KXi64MhinnnnnUbB6jgfhnmfmEJrwcX5hzHOgHZDgfhwWeb1mYBltcA3QfYdhQJLGYNJnrBopNUlAFBEVr9zmQQMX7HnRVnQLGWCW3mjgxhlIvmbT1mgQBWV5nB5gWNBWqhq56WRH1mxG+a1QJ8CB4NRWaHnQ8W9X6qZXDhGMGjCAFW2H2GVV1QHZbqdXHCbo2ie9noyG4UYNwCsULWpXjajgCo5qDliXLXSWVx95vXQXEBXW-U7r1mPW+ZwVrBdgrG-WiAA2AMg32GrXFlDhCmoaCpbaDkHXRL2GCwFBM2E3c6CGXm02lAHo62Po64Sy4Mnx82XGQ3DgDQcp51ioZg3bK3sHSilRqA1Rcx63xkk33XIW3YDbEAOolAa5HdO3oo83LX8W+2xhvtWNgAEBWMzsx3o28Bl3V3EVE2Z5k32HU2NmcchxCBaUaxJHpHdGZhHZ0pOSW4CBacQQTNOJtgHodArI3FjI2KyV8W65mjcQFgFh+8n9iyMHt3GXd20avgsZWAz3hH6BQPCAb3El73F2+ZoXVdX2XB33AWDQv2yG0H3i852A2XTMQPozn4IOrnoPLXFY4OYxEP6J230Hc3u2d2eO+3PhOjcP1n8ObB42iPgUU3SPQwS0ghOW+QB5OwxgQoN3UPRP0PxPMPDhhh+g8ppP2Hrigh5OG3VgeJgxIAB5H7PM7KO29OUJHKoVEzlzRjWC5ND9vLf7zC2A9K1KmMb97PJheF+EplqLxmkWeWaBttNUlyzyTm8QRy2LsGCL+8V4L6iXDgkCwwH8BkPovPUvoVzopybBRsjPvwxhTBwU91HAbwJgcBrJbJckyuyDU7asZVKuUZnBshdklgCgTzcA+ukzEhzF1EmhDhlIGJlIMhDg1hFUwUMvOuUuyCd56AkwSBUBuoZ9LFIMDRmyXp09MDaXKGJnUuUW+bNvkyZz3Iysdu9vyCboTvlsUKLuK2wZrvkXFYuuHu8Rvzitnu-DXuFgKC6gvBduPQc78vBGjgK3CvlV7uMDWcWAi60cQY7X-Hz6HQjwoxvimdaTywQYHpasQj+BEVhA6ZRRgHCAM5lJvwGJBhio8osFApgojajPYBlJXh1SqImT6Im8mhYBXhim-wmg-xPhXhPhsOmhwVXhbWBWmgGJXg3ieu6heg2dQgB5lJc6ziiG0eMimBGL8gYqceBW8fWBs7v2ifonGchxSeFRyfQ8wgqeo5Qhb56fcImeWe2eioOeTGXze5rW+fXgQAEm0Vhfn5Re4AJepfyTZf5e0pkcleVfKA1eNf1itewg-wzfal8h9fDfwzjfTyyD0hdesf5IrfSgmB8f7fJaq6v4SfZE7g3fKfqdqfve6fSkbB-fWf2fOecE+R5IPBvxYBlGM1+hVGO1a65b66Fasqh0TZw6R-THSkBNQ-Xmi2I-BeWFgm4+3AxfE-peU+FfIAM-Pss-IB1fNeoewgdfMf9eJ-YA1-+hS-86JzJvTfzeBbse14a3g31t65JCezfD+ETjb4GJXeDDLvu5h7608SkbSAflugD7D8Q+Y-N-tP3Dpz9T0C-AGkvwsiN1kAH-DfiPjaTb8eehLQ4BHyj4H8IYR-OvOQFP6S9z+cvS-tfztbZ8H+irCcgX3-6v9J+H-L-uX0nLlcMeoQHeHX2oAgC7e4AvkPKEOjIAsw+8NAgyGlBZdtez8F-spHBSIBlB3QOdre1W6o8K+yZNnP-2kFAD6+jfBQbYCUGCRVBk8CQBoKra1YBBRfXAPr30GGCv+TUMweIK26mpbyz0J2NQOtYx0CmwwMNLAFnAZADkBUb8FeUGBDw8+uAG8uuX8G80f+3nSQVjwyTrlGCT5CIUW3HSxpNqVtApkVFnBDww0I1dIc-1CCZCno2Q2xPChN47xPBTFaBFmFMBLAWM-uWgKUKCSzhZwjgMYN+EcAFQMgjgK2o4H6ADxHAdXCYcMGWGDAFhsARwGbW2GzDw0jgDILMP6CxpHAOUE4RkC2EDwcoCwmYDcMcADwio6Qv8JAlMBtD9WuQiQToKkG8Buh+QSAL0JcADDxBoQEYctDGETCphMwuYbcMWHLCxgqw9YZsO2FFRdhEwpYYcIWEnCzhBwy4dcP6AwjbhDwxoV8NoDPDXhxg4jkb0CG-8uhaaORo6E8K7E+IoI3GMMHTA5RBgvRYajMFyidZEAY6DNDlGQCxhGajNCHAcnTBFQFgI7dMNKPxGIB0hp9XLFeFOCpoxgGwikYp11btC7u5gu0LSLGC0dM0DIuIkyNOAsijggkDegVBWrzUiok1NarjVjSIARqyAc2umDDqdUcox1BYNvX5GIBt6U1GMO3lmoTVBgRUaoccIWAbJEAa1ROpNQKhJ0g69NM4Y8jNrh0FgmaMdLvTGpYBoxCwMtvyOGD5QuAiAKUT1TOG5MuAUo-oMNRyhLB6xEMRUYyJVEZC00GaNYZqLvZUiCAvSEMQoEJI954Q0UXsOuwB4m8LRhwAeCgGn6QANkCw64THWUYRtY0t2TsJ8HSHQN4CvSGbG8JSS9iIcSKQkqlFYjCAyko4oTrqKCHR5Jx04yQCbDnF4jFxByZcYMFXF6B1xm4vcGMCwCgRL6AIezkZQPyIUzKZ3TbDFgVjAZVK3+dSgUmOgYgAwvnT0ksR8p-1gukKaCZJXwBASTKSFLWPYWy5EU8uhwZHubDqATd-c8PObgtyW6XRasMPCHtw1IlnVtB1fEvkcAK5kT8+hfOpOxOmR0TWJugt-iII4kCTuJgg5SMJJn7cNOJLEp-iSJ8EGCnBMksSRkJ4nF89BSklQSpK4kZC1yrQ0SbpKaGkj9JEwHSXJIyEvDzJE5YyWSOsm1YlR8RNseqPsl1BHJZo5yR2NclhAtxs4HcfQG8m4AtxP4v8YZKvowAvW1kMUv1BwxHYPowGP3GeQQlqAqqJJb+mNwolJSlA03SxJiBBTNkgqImA7kwGCb2hck2DOSocD-DFNYAsADILkSpj2doGHwyvh0hha5cHQFUo4PN0W6NTCG34XOLSWKyiZ0K44vUWl1NStdAsNkRFJ1N2iVS6uDXJri1za4zSNu40vqTAAGnpEMwKAd5IfGS7jTHQg03JPGF2w1ZuALxAvCgHQBdTDgi0xrksN2bRShkfuI1ox3KYtTo8m0mHCdN2kjSDpHQo6SD06A7AwJqYKtgtPq6PTHAgPdHrwBBlgy5yCwH6dtKGnuQAZGeK8b-2Iwnj+SkMo4A9Ka5wzlgM5PGfQBRn5S0Z9jMkoeD3BqoSMmRFVJRNVh9ADgd0omQPE4l6hr6zZA4OvDOhbxKSoGfeHxG25sB94wIAHPFnASXxr4NoOBA-HFqvxYsBCDMu5VSnwxv6XpFYrohowwCjEiiRWTlN4CgNEeL4+zqU1VwEz5G9nFpPLNvj3xeAtgEHtIE0ALBNB805RnnQYTlpEUkTA4PQDSZQV+oIQM+tFAdmKy-Zj6Y6TtIJnuE7ZjCCJmUiDnoUmgkc5RLiGCb-RTprJF+Oai6lFQfZycjEKnJDlt5qGCWd6c7gYYHAnqfIL6LLOFpfRPZWwOSnlE5DFylA-slOd7DTlZzfMuSTMIrHmYo40EUMAMDzIjLUcZG9IyYNMFo6cteAAYTWfQBNAhAXAALGRvPO4BzBq4eUvBjay5ltzZWS3E+Ta2-BUxKpYwPQFfNlamA75NrcFI-LGCdgX5DEF+QAEUX5HgF+X+Bfkbjz5YwYpi-NHhAKpOQCgAFqPzZwYwGBZ83Pm1CYFZ8w+bOEvmILb5iC1sDAofmILnCMC5+YgrfmIL5WiCj+Ygu-mILf5iC-+YgsAWoKpUMCsBagoACaMC6BefNgBwLOFsAR+bAGPmHzYA6CwRZgsEXYLOFuCwRZAj4WELBFxCwRaQsEXkLBF1CwRSAs4WMLOFzCxHrQIgWCK2FnCjhYfIHgoKdFA8fBefIHjSLLF8isxcorMVGKdFFwx+YcJcWiKnF4iw+RkFUVOLaFXi+hTos3SPzvwFiw+d+GsVhLbFC0+xQtJ8WVS9A3Cw+R80fl6ABFOivQKYviXCL0l7i+JZ4vSWSL0lsi9JVEqOB6BFF6S-wCksoVJK4lZSvxekoCXxL1FSS7RfEoMWHzWwESnRa2FKXBIKllU1sHUuCRNKjgrYFpTotMBpLKppgTJUcAa6PzTAfSrdIspiXzKalky4ZTukWWjLDgzhOZXsr6XOE1leyqpefMgQHLIEuSo4JAnyWVSXhj8yBH0sgQDKblZyw+ZAmGWQI2lNyjpTosgSOLKp4KRJTovBQILD54KXhefPBSFKgV3SoFcMshSPzwUuy8FBMqBWaKIVfyyqVp0fmdgoVh8zsNMqOCdgDlnYbJTiuuWHBOwdyklfCpJXFKcVfSzsK8upUnLOw7ynRZ2A2U4rhlnYBpTit2Wdh0VJKzFVyp+XUq9FXK7FSSsBXdSQVlU5SASp0W9Tz5zPR+cpCpXboNVjK7qScuUicrFVwy5SCKrm5yrDgDEPpf4AVVHB-ABy-wBSttVUr-AtKw4P4HpVurdVbqq1ayv8DDL-AAq21bsv8ASr-AMqw4J-JtWHAPAByjwCco8CBro1pqjwBKr-BRq-w4KnRX+GVWVS-wxKqqQcr-BUrU0j8v8LCqOB-hQlWaj1XkVLV9KVIpak5X+GGUNTz5MvUtWKtzVSrc14av8OarPiPzPg+az4I6p4ZUrPgrqz4FWsqmfAPVVKQdX0s+CsqQEg64ZY4kHWdqvgEqz4OauKZRrimVK4pn0sl6Pzim4a4puaqlRRqpUOao4FKgOVSoqVUqctYcClSsqpUpq4eKOuHiJqWFBylhbssgVRrIFfSyBaPDs6EM7EMwNln7C1jKtyM1+YuLwCbLoVl5KUlAGlNNDLB1WKrU4PG0xCytL5OiuVucGvn-ynFIClVXAp0UMReFWauBZyCAA)

**Comment by philipatkinson** [comment]
I guess this is question of whether it is reasonable to support optional chaining on the (possible) cf property or not? My pull request was ultimately because I do use optional chaining (rather than the property check method noted above). Seems that both are technically valid?

**Comment by Qantas94Heavy** [comment]
While the type is technically valid, the change did break existing code in a minor version upgrade. As such I'd support allowing optional chaining again and leaving any discussion of changing this to V4.

**Comment by caass** [comment]
Yeah, I see the issue. I wonder if there's a way to have the type be both semantically correct and also allow optional chaining...

**Comment by lostpebble** [comment]
This is quite a big regression and the solutions are very unwieldy.

This is one of those niggles of TypeScript for me- when you are creating a large union type with `|` (or) - you need to actually include all the properties in each object type (just mark them as `{ city?: undefined }` if they are undefined in a specific form). Or have an enum propery we can check against to discriminate between them.

If TypeScript can't know for sure that a property within an object exists (even if it exists in one of the subsets of the union types), it will throw this error we see here.

> Yeah, I see the issue. I wonder if there's a way to have the type be both semantically correct and also allow optional chaining...

I think doing what I suggested above (actually naming the properties but making them `?: undefined`) _should_ work...
