### ISSUE TITLE
(3.18.0) IncomingRequestCfPropertiesGeographicInformation is the wrong type

### ISSUE THREAD

**Issue by davemurphysf** [cloudflare/workers-types#313]
Because `IncomingRequestCfProperties` is a union, you can't pass an empty object as a possible type for `IncomingRequestCfPropertiesGeographicInformation`. Instead, all properties should be marked as optional and the `country` 
parameter should be type `country: Iso3166Alpha2Code | "T1";`

**Comment by philipatkinson** [comment]
Probably should have initially named the title in the pull request more explicitly (have done so now), but #310 is exactly that fix.

**Comment by davemurphysf** [comment]
Awesome!  Thank you, closing.
