### ISSUE TITLE
List keys via for-await-of

### ISSUE THREAD

**Issue by CrockAgile** [cloudflare/workers-types#32]
First, I know this is not the right place for this question. But I can't find the official worker runtime. Maybe it is an internal project?

I had an idea for a small extension to the runtime, but I don't know where to ask the question. That's why I have landed here and I thank you for your patience 🙇 .

My desired extension would be to simplify listing of keys, by using "[for await...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of)".

The current API allows for queries by prefix, but only up to a single 'limit' worth of items. Iterating for more items can be a bit awkward:
```js
const value = await NAMESPACE.list({"prefix": "user:1:"})
let list_complete = value.list_complete

while (!list_complete) {
  const cursor = value.cursor

  const next_value = await NAMESPACE.list({"cursor": cursor})
  list_complete = next_value.list_complete
  // use values
}
```

This can be improved by supporting the "[Symbol.asyncIterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator)" API. With that extension, iterating values could be as easy as:

```js
for await (const value of NAMESPACE.list({"prefix": "user:1:"})) {
  // use values
}
```

I hope that this proposal may be passed along, or you can point me in the right direction of where to take this feedback. But I also know that this may have been intentionally omitted. So either way, thanks for reading this 👍

**Comment by GregBrimble** [comment]
Hi @CrockAgile ,

I'm not affiliated with this `workers-types`, but in my own projects, I've been using something like this, which might be of use to you:

```js
async function* listAll(namespace, options) {
  let cursor;
  let hasNextPage = true;
  while (hasNextPage) {
    const results = await namespace.list({ ...options, cursor })
    const { keys: queue } = results
    hasNextPage = !results.list_complete

    while (queue.length > 0) {
      const key = queue.shift()
      if (key !== undefined) yield key
    }
  }
}
```

Which then allows you to use a for await...of loop in an async function:

```js
for await (const key of listAll(NAMESPACE, {"prefix": "user:1:" })) {
  // use key
  // e.g. await NAMESPACE.get(key.name)
}
```

As an unrelated aside, your key generation looks very similar to that of my own project's [kv-orm](https://github.com/kv-orm/core/). I'd be very interested to hear about what you're working on, if kv-orm could be of any use, and/or if I could learn anything from what you're working on. My email is in [my profile](mailto:developer@gregbrimble.com). Please get in touch!

**Comment by CrockAgile** [comment]
Thanks for the example @GregBrimble ! Glad to know I am not the only one hitting this use case. I'm not working on anything interesting. I am building a minimal app just to learn my way around CF workers. I'll give kv-orm a look since it seems to be a more full feature version of the hacky data model I am using for this small test project.
