### ISSUE TITLE
NPM Release @cloudflare/worker-types 4.20221111.0

### ISSUE THREAD

**Issue by RobinSCU** [cloudflare/workers-types#321]
Hi,

was the NPM release "@cloudflare/worker-types 4.20221111.0" an intentional release?

![image](https://user-images.githubusercontent.com/50205066/202709773-72a4b9cd-4104-466d-82fc-580da4f467fd.png)
https://www.npmjs.com/package/@cloudflare/workers-types?activeTab=versions

The version number changed and it is now a different Repo URL

Best
Robin

**Comment by penalosa** [comment]
https://blog.cloudflare.com/improving-workers-types/

**Comment by MichaelDeBoey** [comment]
@penalosa What does that mean for the Remix Cloudflare adapters/runtime/templates?

Can the runtime/adapters just add ` || ^4.20221111.0` to `peerDependencies`?
- https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/packages/remix-cloudflare/package.json#L24
- https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/packages/remix-cloudflare-pages/package.json#L25
- https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/packages/remix-cloudflare-workers/package.json#L25

Should the runtime/adapters add compatibility date imports to their `tsconfig.json` files?
If so, would you recommend it be `2022-08-04` or `experimental`?
- https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/packages/remix-cloudflare/tsconfig.json#L7
- https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/packages/remix-cloudflare-pages/tsconfig.json#L7
- https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/packages/remix-cloudflare-workers/tsconfig.json#L7

What about our templates?
Should they add a compatibility date to the type reference in `remix.d.ts`?
If so, what import would you recommend here? `2022-08-04`? `experimental`? Something else?
- https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/templates/cloudflare-pages/remix.env.d.ts#L3
- https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/templates/cloudflare-workers/remix.env.d.ts#L3
