### ISSUE TITLE
Unioned cf type on RequestInit does not allow re-assignment of properties

### ISSUE THREAD

**Issue by third774** [cloudflare/workers-types#37]
The unioned type introduced by PR https://github.com/cloudflare/workers-types/pull/18 does not allow re-assignment of properties. Consider the following snippet:

```ts
// this assignment works just fine
let init: RequestInit = {
  cf: {
    cacheKey: 'foo',
  },
}

if (init.cf) {
  // but re-writing properties is prevented by the type checker
  init.cf.cacheKey = 'bar'
}
```

This produces the following type error:

![image](https://user-images.githubusercontent.com/8732191/83198783-89618700-a105-11ea-9e99-fbf0da314500.png)

The ideal outcome (if possible) would be to extend the `RequestInit` that `fetch` uses without obstructing the use case above while still supporting the example identified in issue https://github.com/cloudflare/workers-types/issues/15.

Still trying to work out how to do this or if it's possible, but wanted to start a discussion around it :)

**Comment by 1000hz** [comment]
Addressed via #44
