### ISSUE TITLE
Element methods return type mismatch

### ISSUE THREAD

**Issue by jdanyow** [cloudflare/workers-types#42]
bear with me, I'm almost clueless when it comes to Rust...

I noticed many of the Element interface methods return Element:
https://github.com/cloudflare/workers-types/blob/650b496d47132ab9f14eecc1e0bce72fc9f4030a/index.d.ts#L283

It doesn't look like the corresponding lol-html implementation returns Element though:
https://github.com/cloudflare/lol-html/blob/1581355d998dc3cd2664e7264f9e3e6e0a7d4a85/js-api/src/element.rs#L75-L78

**Comment by ObsidianMinor** [comment]
We don't use that wasm-js API in Workers as it's not complete and would be too slow (since it'd run in wasm, not native). The current API you see now is correct.
