### ISSUE TITLE
Type definition missing for KVNamespace.getWithMetadata()

### ISSUE THREAD

**Issue by neodon** [cloudflare/workers-types#57]
Thank you for maintaining this package--it makes writing worker code so much easier.

I noticed there is a new method for KVNamespace: `getWithMetadata()`.  It is not in the type definitions, however, so I've had to patch it in myself:

```typescript
declare global {
  export interface KVNamespace {
    getWithMetadata(key: string): KVValue<{ value: string; metadata: any }>
  }
}
```

I'm sure that is not quite the best way to type the function.  If you could add the proper type definition, I will give my cat an extra treat.

I may attempt to add the proper type definition and submit a PR.

**Comment by GregBrimble** [comment]
Hey @neodon ! I've got a PR up for just that right here, #54 . We were just getting it reviewed, but it slipped through the cracks. We'll try get it merged in shortly.

cc @ispivey

**Comment by neodon** [comment]
Thank you!  My PR looked quite similar, but I missed a couple things.  Glad you're already on top of things.

**Comment by koeninger** [comment]
released in https://github.com/cloudflare/workers-types/releases/tag/v2.1.0
