### ISSUE TITLE
File index.d.ts is not a module

### ISSUE THREAD

**Issue by minhducsun2002** [cloudflare/workers-types#85]
VSCode is giving the `File '/home/myuser/Projects/worker/node_modules/@cloudflare/workers-types/index.d.ts' is not a module` error for me.

I'm working on a new project generated using `yarn wrangler generate`, using the template at https://github.com/cloudflare/worker-typescript-template.

Any solution to this? :thinking:

**Comment by patlux** [comment]
Remove

```ts
import type { ... } from '@cloudflare/workers-types'
```

in your source files and add

```json
{
  "compilerOptions": {
    "types": ["@cloudflare/workers-types"],
  }
}
```

to your `tsconfig.json`.
