### ISSUE TITLE
DurableObjectStorage transaction method signature

### ISSUE THREAD

**Issue by sbfaulkner** [cloudflare/workers-types#88]
looking at...
https://github.com/cloudflare/workers-types/blob/ebb20431d036d8a68bc877e8b14b8b7e6675071b/index.d.ts#L656-L658

should the `txn` argument for the closure perhaps be of type `DurableObjectTransaction` ?

**Comment by koeninger** [comment]
Seems that way, yeah - would you like to open a PR to fix it?

**Comment by sbfaulkner** [comment]
@koeninger #89
