### ISSUE TITLE
KV.put `FormData` type?

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-types#94]
Can KV store FormData types? It doesn't seem so according to the [docs](https://developers.cloudflare.com/workers/runtime-apis/kv#parameters), and how would you even get that data back out with `KV.get`? There's certainly no documented type there.

Line in question: https://github.com/cloudflare/workers-types/blob/673e0cb4ec6b102ac14bbf8718bc3622bf5d66f5/index.d.ts#L625

**Comment by koeninger** [comment]
No it can't, trying to call KV.put on a FormData will result in 

"name":"TypeError","message":"KV put() accepts only strings, ArrayBuffers, ArrayBufferViews, and ReadableStreams as values."

Do you want to put in a PR to remove FormData from those types?
